### PR TITLE
Remove argparse

### PR DESCRIPTION
**Pull request by fabaff**
`argparse` is a Python [standard module](https://docs.python.org/3/library/argparse.html).

### CODE REVIEW

**Comment by fabaff** [comment]
`argparse` became a standard module in Python 3.2. Your `pyproject.toml` says >= [3.6](https://github.com/ivan-sincek/forbidden/blob/main/pyproject.toml#L11), thus all distributions will need to patch `argparse` out of your `pyproject.toml` file to be able to build their packages. 

> The PyPi argparse package is mostly for people who want to have argparse on
older Pythons, like < 2.7 or < 3.2 because it was not in stdlib back then.

from https://github.com/ThomasWaldmann/argparse/blob/master/README.txt

Please reconsider your `wontfix`. Thanks you.

**Comment by ivan-sincek** [comment]
Hi,

Thank you for the clarification, I understand this.

I set this MR as `wontfix` because I do not see any implications with keeping the dependecy, other than having the cleaner code, etc. However, I will reconsider this on the next release.

Kind regards,
Ivan.

**Comment by branchv** [comment]
fyi, I came here to make the same change for Homebrew. 

The implications with keeping the dependency (beyond being unnecessary and causing extra work for distributors) is that it forces on your users a frozen, long outdated version of `argparse` (last release was 9 years ago) that will never benefit from any bug/security fixes and risks incompatibility with future versions of python

**Comment by ivan-sincek** [comment]
Okay guys, you win! 😄

Thank you for all the explanations! As I dabble in programming, I was not aware of any implications.

I will release the new version first thing tomorrow.

Kind regards,
Ivan.

**Comment by ivan-sincek** [comment]
New release has been pushed. Thank you @fabaff and @branchvincent for pointing this out and giving the explanation, I gave you both credits in the release page.

**Comment by branchv** [comment]
Thanks for reconsidering @ivan-sincek and for the quick release! Really appreciate it

**Pull request closed without merging**
